require 'xcodeproj'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

project_path = './IapExample.xcodeproj'
project = Xcodeproj::Project.open(project_path)

# Fetches minimum deployment target version from the project and sets it as the default
config_list = project.root_object.build_configuration_list
debug_config = config_list.build_configurations.find { |config| config.name == 'Debug' }
min_ios_version = debug_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
default_min_ios_version = '12.4'
if min_ios_version.nil? || min_ios_version.empty?
  puts "IPHONEOS_DEPLOYMENT_TARGET not set at the project level for Debug configuration. Using default value of #{default_min_ios_version}"
  min_ios_version = default_min_ios_version
else
  puts "Minimum iOS version set to: #{min_ios_version}"
end
platform :ios, min_ios_version || default_min_ios_version

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'IapExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'IapExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Fixes an issue where the build would fail if a Pod's deployment target was set to a lower version than the minimum supported version on the project
    puts "\nChecking if the deployment targets for Pods are set to the minimum supported version of \033[33m#{min_ios_version}\033[0m or higher."
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        current_target_version = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if Gem::Version.new(current_target_version) < Gem::Version.new(min_ios_version)
          puts "\033[33m#{target.name} deployment target of #{current_target_version} is too low. Updating...\033[0m"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version
        end
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
